<?php

namespace SwitchBox\DHT;

// An (initial) seed with all information needed to connect to it.

use SwitchBox\KeyPair;

class Host {
    protected $name;               // Hex string of hash / nodename
    protected $public_key;         // Public key of the node in PEM format
    protected $ip;                 // IP that connected
    protected $port;               // Port that connected

    /**
     * @param $host_or_ip
     * @param $port
     * @param $public_key
     */
    public function __construct($host_or_ip, $port, $public_key)
    {
        $this->ip = gethostbyname($host_or_ip);
        $this->port = $port;
        $this->public_key = $public_key;

        $this->name = self::generateNodeName($public_key);
    }

    /**
     * @param $public_key
     * @return string
     */
    public static function generateNodeName($public_key)
    {
        return hash('sha256', KeyPair::convertPemToDer($public_key));
    }

    /**
     * Nodename, as generated by the public key
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * @return mixed
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * @return mixed
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * @param mixed $public_key
     */
    public function setPublicKey($public_key)
    {
        $this->public_key = $public_key;
    }



    /**
     * @return string
     */
    function __toString()
    {
        return $this->getIp().":".$this->getPort()."[".$this->getName()."]";
    }

}
